# Generated by Django 5.1.5 on 2025-01-30 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_profile_address1_alter_profile_address2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='country',
        ),
    ]
